/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ANNA.glb
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/ANNA.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Anna_Tongue" geometry={nodes.Anna_Tongue.geometry} material={materials.Vray_Tongue} scale={0.01} />
        <group name="Anna_Head" scale={0.01}>
          <mesh name="Mesh001" geometry={nodes.Mesh001.geometry} material={materials['Material #38']} />
          <mesh name="Mesh001_1" geometry={nodes.Mesh001_1.geometry} material={materials['Material #39']} />
        </group>
        <mesh name="Anna_Eyes" geometry={nodes.Anna_Eyes.geometry} material={materials.Vray_Eyes} scale={0.01} />
        <group name="Anna_Eyebrows" scale={0.01}>
          <mesh name="Mesh003" geometry={nodes.Mesh003.geometry} material={materials['Material #55']} />
          <mesh name="Mesh003_1" geometry={nodes.Mesh003_1.geometry} material={materials['Material #56']} />
        </group>
        <group name="Anna_Teeth" scale={0.01}>
          <mesh name="Mesh004" geometry={nodes.Mesh004.geometry} material={materials.Std_Upper_Teeth} />
          <mesh name="Mesh004_1" geometry={nodes.Mesh004_1.geometry} material={materials.Std_Lower_Teeth} />
        </group>
        <group name="Anna_Hair" scale={0.01}>
          <mesh name="Mesh005" geometry={nodes.Mesh005.geometry} material={materials.Vray_hair} />
          <mesh name="Mesh005_1" geometry={nodes.Mesh005_1.geometry} material={materials.Vray_scalp} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/ANNA.glb')
