/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 Car_Test_02.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Car_Test_02.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.mesh_back_door.geometry} material={materials.pasted__body} />
        <mesh geometry={nodes.mesh_back_glass.geometry} material={materials.pasted__glass} />
        <mesh geometry={nodes.mesh_back_glass_fire.geometry} material={materials.lambert18} />
        <mesh geometry={nodes.mesh_back_L_Lamp.geometry} material={materials.pasted__plastic} />
        <mesh geometry={nodes.mesh_back_L_Lamp_bottom.geometry} material={materials.pasted__plastic} />
        <mesh geometry={nodes.mesh_back_L_tyre.geometry} material={materials.pasted__tyre} />
        <mesh geometry={nodes.mesh_back_L_tyre_fire.geometry} material={materials.lambert9} />
        <mesh geometry={nodes.mesh_back_R_Lamp.geometry} material={materials.pasted__plastic} />
        <mesh geometry={nodes.mesh_back_R_Lamp_bottom.geometry} material={materials.pasted__plastic} />
        <mesh geometry={nodes.mesh_back_R_tyre.geometry} material={materials.pasted__tyre} />
        <mesh geometry={nodes.mesh_back_R_tyre_fire.geometry} material={materials.lambert16} />
        <mesh geometry={nodes.mesh_body_bottom.geometry} material={materials.pasted__plastic} />
        <mesh geometry={nodes.mesh_body_top.geometry} material={materials.pasted__body} />
        <mesh geometry={nodes.mesh_front_door.geometry} material={materials.pasted__body} />
        <mesh geometry={nodes.mesh_front_door_fire.geometry} material={materials.lambert13} />
        <mesh geometry={nodes.mesh_front_glass.geometry} material={materials.pasted__glass} />
        <mesh geometry={nodes.mesh_front_glass_fire.geometry} material={materials.lambert12} />
        <mesh geometry={nodes.mesh_front_L_Lamp.geometry} material={materials.pasted__plastic} />
        <mesh geometry={nodes.mesh_front_L_mirror.geometry} material={materials.pasted__plastic} />
        <mesh geometry={nodes.mesh_front_L_mirror_fire.geometry} material={materials.lambert7} />
        <mesh geometry={nodes.mesh_front_L_tyre.geometry} material={materials.pasted__tyre} />
        <mesh geometry={nodes.mesh_front_L_tyre_fire.geometry} material={materials.lambert6} />
        <mesh geometry={nodes.mesh_front_R_Lamp.geometry} material={materials.pasted__plastic} />
        <mesh geometry={nodes.mesh_front_R_mirror.geometry} material={materials.pasted__plastic} />
        <mesh geometry={nodes.mesh_front_R_mirror_fire.geometry} material={materials.lambert15} />
        <mesh geometry={nodes.mesh_front_R_tyre.geometry} material={materials.pasted__tyre} />
        <mesh geometry={nodes.mesh_front_R_tyre_fire.geometry} material={materials.lambert14} />
        <mesh geometry={nodes.mesh_L_door.geometry} material={materials.pasted__body} />
        <mesh geometry={nodes.mesh_L_door_fire.geometry} material={materials.lambert8} />
        <mesh geometry={nodes.mesh_L_glass.geometry} material={materials.pasted__glass} />
        <mesh geometry={nodes.mesh_L_glass_fire.geometry} material={materials.lambert10} />
        <mesh geometry={nodes.mesh_number_area.geometry} material={materials.pasted__plastic} />
        <mesh geometry={nodes.mesh_R_door.geometry} material={materials.pasted__body} />
        <mesh geometry={nodes.mesh_R_door_fire.geometry} material={materials.lambert11} />
        <mesh geometry={nodes.mesh_R_glass.geometry} material={materials.pasted__glass} />
        <mesh geometry={nodes.mesh_R_glass_fire.geometry} material={materials.lambert17} />
      </group>
    </group>
  )
}

useGLTF.preload('/Car_Test_02.glb')
