/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 Car_Test_05.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Car_Test_05.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.mesh_back_door.geometry} material={materials.body1} />
        <mesh geometry={nodes.mesh_back_glass.geometry} material={materials.glass1} />
        <mesh geometry={nodes.mesh_back_glass_fire.geometry} material={materials.mesh_back_glass_FIRE} />
        <mesh geometry={nodes.mesh_back_L_Lamp.geometry} material={materials.plastic1} />
        <mesh geometry={nodes.mesh_back_L_Lamp_bottom.geometry} material={materials.plastic1} />
        <mesh geometry={nodes.mesh_back_L_tyre.geometry} material={materials.tyre1} />
        <mesh geometry={nodes.mesh_back_L_tyre_fire.geometry} material={materials.mesh_back_L_tyre_FIRE} />
        <mesh geometry={nodes.mesh_back_R_Lamp.geometry} material={materials.plastic1} />
        <mesh geometry={nodes.mesh_back_R_Lamp_bottom.geometry} material={materials.plastic1} />
        <mesh geometry={nodes.mesh_back_R_tyre.geometry} material={materials.tyre1} />
        <mesh geometry={nodes.mesh_back_R_tyre_fire.geometry} material={materials.mesh_back_R_tyre_FIRE} />
        <mesh geometry={nodes.mesh_body_bottom.geometry} material={materials.plastic1} />
        <mesh geometry={nodes.mesh_body_top.geometry} material={materials.body1} />
        <mesh geometry={nodes.mesh_front_door.geometry} material={materials.body1} />
        <mesh geometry={nodes.mesh_front_door_fire.geometry} material={materials.mesh_front_door_FIRE} />
        <mesh geometry={nodes.mesh_front_glass.geometry} material={materials.glass1} />
        <mesh geometry={nodes.mesh_front_glass_fire.geometry} material={materials.mesh_front_glass_FIRE} />
        <mesh geometry={nodes.mesh_front_L_Lamp.geometry} material={materials.plastic1} />
        <mesh geometry={nodes.mesh_front_L_mirror.geometry} material={materials.plastic1} />
        <mesh geometry={nodes.mesh_front_L_mirror_fire.geometry} material={materials.mesh_front_L_mirror_FIRE} />
        <mesh geometry={nodes.mesh_front_L_tyre.geometry} material={materials.tyre1} />
        <mesh geometry={nodes.mesh_front_L_tyre_fire.geometry} material={materials.mesh_front_L_tyre_FIRE} />
        <mesh geometry={nodes.mesh_front_R_Lamp.geometry} material={materials.plastic1} />
        <mesh geometry={nodes.mesh_front_R_mirror.geometry} material={materials.plastic1} />
        <mesh geometry={nodes.mesh_front_R_mirror_fire.geometry} material={materials.mesh_front_R_mirror_FIRE} />
        <mesh geometry={nodes.mesh_front_R_tyre.geometry} material={materials.tyre1} />
        <mesh geometry={nodes.mesh_front_R_tyre_fire.geometry} material={materials.mesh_front_R_tyre_FIRE} />
        <mesh geometry={nodes.mesh_L_door.geometry} material={materials.body1} />
        <mesh geometry={nodes.mesh_L_door_fire.geometry} material={materials.mesh_L_door_FIRE} />
        <mesh geometry={nodes.mesh_L_glass.geometry} material={materials.glass1} />
        <mesh geometry={nodes.mesh_L_glass_fire.geometry} material={materials.mesh_L_glass_FIRE} />
        <mesh geometry={nodes.mesh_number_area.geometry} material={materials.plastic1} />
        <mesh geometry={nodes.mesh_R_door.geometry} material={materials.body1} />
        <mesh geometry={nodes.mesh_R_door_fire.geometry} material={materials.mesh_R_door_FIRE} />
        <mesh geometry={nodes.mesh_R_glass.geometry} material={materials.glass1} />
        <mesh geometry={nodes.mesh_R_glass_fire.geometry} material={materials.mesh_R_glass_FIRE} />
      </group>
    </group>
  )
}

useGLTF.preload('/Car_Test_05.glb')
